# constants.py

### VISUALS
CHAR_MINE = '*'
CHAR_FLAG = 'F'
CHAR_UNREVEALED = '/'
COLUMN_TITLES = '12345678910'
ROW_TITLES = 'ABCDEFGHIJ'

### GAME CONFIG
DEFAULT_ROWS = 10
DEFAULT_COLS = 10
DEFAULT_MINE_COUNT = 10

### INPUT
KEY_QUIT = 'q'

### UTILS
LETTER_TO_ROW = {chr(i + ord('A')): i for i in range(DEFAULT_ROWS)}